services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - data:/data
    env_file:
      - .env-docker
    depends_on:
      db:
        condition: service_healthy
    networks:
      - practicare-network
    environment:
      PYTHONPATH: src

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: practicare
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - practicare-network

  celery_worker:
    build: .
    command: celery -A src.celery_app worker -l info --concurrency=2
    volumes:
      - data:/data
    env_file:
      - .env-docker
    depends_on:
      - redis
    networks:
      - practicare-network

  flower:
    build: .
    command: celery -A src.celery_app flower --port=5555
    env_file:
      - .env-docker
    ports:
      - "5555:5555"
    depends_on:
      - redis
    networks:
      - practicare-network

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    networks:
      - practicare-network

networks:
  practicare-network:
    driver: bridge

volumes:
  postgres_data:
  data:
