services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    networks:
      - practicare-network
    restart: unless-stopped

  app:
    build: .
    expose:
      - "8000"
    volumes:
      - data:/data
    env_file:
      - .env-prod
    depends_on:
      redis:
        condition: service_started
    environment:
      PYTHONPATH: src
    networks:
      - practicare-network
    restart: unless-stopped


  redis:
    image: redis:8-alpine
    networks:
      - practicare-network
    restart: unless-stopped

  celery_worker:
    build: .
    command: celery -A src.celery_app worker -l info --concurrency=1
    volumes:
      - data:/data
    env_file:
      - .env-prod
    depends_on:
      - redis
    networks:
      - practicare-network
    restart: unless-stopped

networks:
  practicare-network:
    driver: bridge

volumes:
  data:
  caddy_data:
  caddy_config:
