"""added automated record jobs table

Revision ID: 011a4ee65514
Revises: 6590799279e2
Create Date: 2026-01-13 15:59:46.825535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '011a4ee65514'
down_revision: Union[str, Sequence[str], None] = '6590799279e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automated_record_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('user_uuid', sa.String(), nullable=True),
    sa.Column('treatment_uuid', sa.String(), nullable=True),
    sa.Column('treatment_record_uuid', sa.String(), nullable=True),
    sa.Column('audio_path', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'TRANSCRIBING', 'TRANSCRIBED', 'GENERATING_RECORD', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('transcription', sa.String(), nullable=True),
    sa.Column('generated_record', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automated_record_jobs_id'), 'automated_record_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_automated_record_jobs_uuid'), 'automated_record_jobs', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_automated_record_jobs_uuid'), table_name='automated_record_jobs')
    op.drop_index(op.f('ix_automated_record_jobs_id'), table_name='automated_record_jobs')
    op.drop_table('automated_record_jobs')
    # ### end Alembic commands ###
