"""Add is_active to records and reports

Revision ID: 3f281970b121
Revises: b2c3d4e5f6a7
Create Date: 2026-04-07 13:34:26.098706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f281970b121'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment_records', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('treatment_reports', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.alter_column('treatment_reports', 'system_prompt',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('treatment_reports', 'start_date_period',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('treatment_reports', 'end_date_period',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('treatment_reports', 'end_date_period',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('treatment_reports', 'start_date_period',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('treatment_reports', 'system_prompt',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('treatment_reports', 'is_active')
    op.drop_column('treatment_records', 'is_active')
    # ### end Alembic commands ###
