"""Changed foreingKey of treatment to uuid

Revision ID: 44104c1959a2
Revises: e20c8b7c7579
Create Date: 2025-12-29 13:42:31.513722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44104c1959a2'
down_revision: Union[str, Sequence[str], None] = 'e20c8b7c7579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
