"""Initial migration

Revision ID: 4f3cb24d2f6e
Revises: 
Create Date: 2026-01-29 13:55:09.654658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f3cb24d2f6e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automated_record_jobs',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=True),
    sa.Column('treatment_uuid', sa.UUID(), nullable=True),
    sa.Column('treatment_record_uuid', sa.UUID(), nullable=True),
    sa.Column('audio_path', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'TRANSCRIBING', 'TRANSCRIBED', 'GENERATING_RECORD', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('transcription', sa.String(), nullable=True),
    sa.Column('generated_record', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_automated_record_jobs_uuid'), 'automated_record_jobs', ['uuid'], unique=False)
    op.create_table('automated_report_jobs',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=True),
    sa.Column('treatment_uuid', sa.UUID(), nullable=True),
    sa.Column('treatment_report_uuid', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING_REPORT', 'COMPLETED', 'FAILED', name='reportjobstatus'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('generated_report_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_automated_report_jobs_uuid'), 'automated_report_jobs', ['uuid'], unique=False)
    op.create_table('patients',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHERS', name='gender'), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_patients_uuid'), 'patients', ['uuid'], unique=False)
    op.create_table('users',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=False)
    op.create_table('sessions',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('ix_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('ix_sessions_user_uuid', 'sessions', ['user_uuid'], unique=False)
    op.create_table('treatments',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=True),
    sa.Column('patient_uuid', sa.UUID(), nullable=True),
    sa.Column('weekday', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekdays'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['patient_uuid'], ['patients.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_treatments_uuid'), 'treatments', ['uuid'], unique=False)
    op.create_table('treatment_records',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('treatment_uuid', sa.UUID(), nullable=True),
    sa.Column('automated_record_job_uuid', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'FAILED', name='recordstatus'), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('record_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['automated_record_job_uuid'], ['automated_record_jobs.uuid'], ),
    sa.ForeignKeyConstraint(['treatment_uuid'], ['treatments.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('treatment_uuid', 'record_number')
    )
    op.create_index(op.f('ix_treatment_records_uuid'), 'treatment_records', ['uuid'], unique=False)
    op.create_table('treatment_reports',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('treatment_uuid', sa.UUID(), nullable=True),
    sa.Column('automated_report_job_uuid', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'FAILED', name='reportstatus'), nullable=False),
    sa.Column('demand_description', sa.String(), nullable=True),
    sa.Column('procedures', sa.String(), nullable=True),
    sa.Column('analysis', sa.String(), nullable=True),
    sa.Column('conclusion', sa.String(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('start_date_period', sa.Date(), nullable=True),
    sa.Column('end_date_period', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['automated_report_job_uuid'], ['automated_report_jobs.uuid'], ),
    sa.ForeignKeyConstraint(['treatment_uuid'], ['treatments.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_treatment_reports_uuid'), 'treatment_reports', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_treatment_reports_uuid'), table_name='treatment_reports')
    op.drop_table('treatment_reports')
    op.drop_index(op.f('ix_treatment_records_uuid'), table_name='treatment_records')
    op.drop_table('treatment_records')
    op.drop_index(op.f('ix_treatments_uuid'), table_name='treatments')
    op.drop_table('treatments')
    op.drop_index('ix_sessions_user_uuid', table_name='sessions')
    op.drop_index('ix_sessions_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_uuid'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_automated_report_jobs_uuid'), table_name='automated_report_jobs')
    op.drop_table('automated_report_jobs')
    op.drop_index(op.f('ix_automated_record_jobs_uuid'), table_name='automated_record_jobs')
    op.drop_table('automated_record_jobs')
    # ### end Alembic commands ###
