"""add is_update_scheduled to treatment_context

Revision ID: 6990923b39c9
Revises: 3f281970b121
Create Date: 2026-04-08 14:39:58.402819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6990923b39c9'
down_revision: Union[str, Sequence[str], None] = '3f281970b121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment_contexts', sa.Column('is_update_scheduled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatment_contexts', 'is_update_scheduled')
    # ### end Alembic commands ###
