"""add treatment_context and treatment_context_draft

Revision ID: 980a34376d53
Revises: 9973d1bc3fd9
Create Date: 2026-04-02 14:53:30.745222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980a34376d53'
down_revision: Union[str, Sequence[str], None] = '9973d1bc3fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment_contexts',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('treatment_uuid', sa.UUID(), nullable=False),
    sa.Column('life_dynamics', sa.Text(), nullable=True),
    sa.Column('clinical_history', sa.Text(), nullable=True),
    sa.Column('psychological_patterns', sa.Text(), nullable=True),
    sa.Column('therapeutic_goals', sa.Text(), nullable=True),
    sa.Column('medication_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['treatment_uuid'], ['treatments.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('treatment_uuid')
    )
    op.create_index(op.f('ix_treatment_contexts_uuid'), 'treatment_contexts', ['uuid'], unique=False)
    op.create_table('treatment_context_drafts',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('treatment_context_uuid', sa.UUID(), nullable=False),
    sa.Column('treatment_record_uuid', sa.UUID(), nullable=False),
    sa.Column('life_dynamics', sa.Text(), nullable=True),
    sa.Column('clinical_history', sa.Text(), nullable=True),
    sa.Column('psychological_patterns', sa.Text(), nullable=True),
    sa.Column('therapeutic_goals', sa.Text(), nullable=True),
    sa.Column('medication_notes', sa.Text(), nullable=True),
    sa.Column('is_applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['treatment_context_uuid'], ['treatment_contexts.uuid'], ),
    sa.ForeignKeyConstraint(['treatment_record_uuid'], ['treatment_records.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_treatment_context_drafts_uuid'), 'treatment_context_drafts', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_treatment_context_drafts_uuid'), table_name='treatment_context_drafts')
    op.drop_table('treatment_context_drafts')
    op.drop_index(op.f('ix_treatment_contexts_uuid'), table_name='treatment_contexts')
    op.drop_table('treatment_contexts')
    # ### end Alembic commands ###
