"""add_techniques_and_requested_activities

Revision ID: a3050e1e8569
Revises: 6a206c064280
Create Date: 2026-04-22 18:52:39.683888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3050e1e8569'
down_revision: Union[str, Sequence[str], None] = '6a206c064280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment_context_drafts', sa.Column('techniques', sa.JSON(), nullable=True))
    op.add_column('treatment_context_drafts', sa.Column('requested_activities', sa.JSON(), nullable=True))
    op.add_column('treatment_contexts', sa.Column('techniques', sa.JSON(), nullable=True))
    op.add_column('treatment_contexts', sa.Column('requested_activities', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatment_contexts', 'requested_activities')
    op.drop_column('treatment_contexts', 'techniques')
    op.drop_column('treatment_context_drafts', 'requested_activities')
    op.drop_column('treatment_context_drafts', 'techniques')
    # ### end Alembic commands ###
