"""Adding Treatment records and reports

Revision ID: c78261c18389
Revises: bc244da7ba67
Create Date: 2026-01-07 13:58:04.496423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c78261c18389'
down_revision: Union[str, Sequence[str], None] = 'bc244da7ba67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('treatment_uuid', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('record_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['treatment_uuid'], ['treatments.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_records_id'), 'treatment_records', ['id'], unique=False)
    op.create_index(op.f('ix_treatment_records_uuid'), 'treatment_records', ['uuid'], unique=True)
    op.create_table('treatment_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('treatment_uuid', sa.String(), nullable=True),
    sa.Column('demand_description', sa.String(), nullable=True),
    sa.Column('procedures', sa.String(), nullable=True),
    sa.Column('analysis', sa.String(), nullable=True),
    sa.Column('conclusion', sa.String(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('start_date_period', sa.Date(), nullable=True),
    sa.Column('end_date_period', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['treatment_uuid'], ['treatments.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_reports_id'), 'treatment_reports', ['id'], unique=False)
    op.create_index(op.f('ix_treatment_reports_uuid'), 'treatment_reports', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_treatment_reports_uuid'), table_name='treatment_reports')
    op.drop_index(op.f('ix_treatment_reports_id'), table_name='treatment_reports')
    op.drop_table('treatment_reports')
    op.drop_index(op.f('ix_treatment_records_uuid'), table_name='treatment_records')
    op.drop_index(op.f('ix_treatment_records_id'), table_name='treatment_records')
    op.drop_table('treatment_records')
    # ### end Alembic commands ###
