"""Added gender field to patient

Revision ID: f171dbce43fd
Revises: b580c938d9d4
Create Date: 2025-12-31 00:39:28.082910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f171dbce43fd'
down_revision: Union[str, Sequence[str], None] = 'b580c938d9d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHERS', name='gender'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'gender')
    # ### end Alembic commands ###
