"""add context_update to processtype

Revision ID: f71506e547e2
Revises: 980a34376d53
Create Date: 2026-04-03 19:36:37.361666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f71506e547e2'
down_revision: Union[str, Sequence[str], None] = '980a34376d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute("ALTER TYPE processtype ADD VALUE 'CONTEXT_UPDATE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removing values from enums is not directly supported in Postgres
    pass
    # ### end Alembic commands ###
